version: '2'
services:
  app:
    build: src
    volumes:
      - ./src/.env:/var/www/.env
      - storage:/var/www/storage
      - public:/var/www/public
    ports:
      - 9000:9000
    restart: unless-stopped
  web:
    image: nginx
    volumes:
      - public:/var/www/public
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - 8880:80
    restart: unless-stopped

volumes:
  storage:
  public:
